
import { RESOURCE_TYPES } from '../resources/resourceTypes';
import type { IButtonCostList } from '~/interfaces/buttons';

export const MILITARY_BUTTON_TYPES = {
    TRAIN_SPEARMAN: 'trainSpearman',
    UPGRADE_SPEARMAN: 'upgradeSpearman',
    TRAIN_PIKEMAN: 'trainPikeman',
    UPGRADE_PIKEMAN: 'upgradePikeman',
    TRAIN_FOOTPAD: 'trainFootpad',
    UPGRADE_FOOTPAD: 'upgradeFootpad',
    TRAIN_OUTLAW: 'trainOutlaw',
    TRAIN_HALBERDIER: 'trainHalberdier',
    TRAIN_HEAVY_INFANTRY: 'trainHeavyInfantry',
    UPGRADE_HEAVY_INFANTRY: 'upgradeHeavyInfantry',
    TRAIN_SHOCKTROOPER: 'trainShocktrooper',
    UPGRADE_SHOCKTROOPER: 'upgradeShocktrooper',
    TRAIN_SIEGETROOPER: 'trainSiegetrooper',
    TRAIN_MAGE: 'trainMage',
    UPGRADE_MAGE: 'upgradeMage',
    TRAIN_GREAT_MAGE: 'trainGreatMage',
    TRAIN_ARCH_MAGE: 'trainArchMage',
    TRAIN_THUNDERER: 'trainThunderer',
    UPGRADE_THUNDERER: 'upgradeThunderer',
    TRAIN_THUNDERGUARD: 'trainThunderguard',
    UPGRADE_THUNDERGUARD: 'upgradeThunderguard',
    TRAIN_DRAGONGUARD: 'trainDragonguard',
    DISABLED_TRAIN: 'disabledTrain',
    DISABLED_UPGRADE: 'disabledUpgrade',
}

export const MILITARY_BUTTON_TEXTS = {
    [MILITARY_BUTTON_TYPES.TRAIN_SPEARMAN]: 'Train',
    [MILITARY_BUTTON_TYPES.UPGRADE_SPEARMAN]: 'Upgrade',
    [MILITARY_BUTTON_TYPES.TRAIN_PIKEMAN]: 'Train',
    [MILITARY_BUTTON_TYPES.UPGRADE_PIKEMAN]: 'Upgrade',
    [MILITARY_BUTTON_TYPES.TRAIN_HALBERDIER]: 'Train',
    [MILITARY_BUTTON_TYPES.TRAIN_FOOTPAD]: 'Train',
    [MILITARY_BUTTON_TYPES.UPGRADE_FOOTPAD]: 'Upgrade',
    [MILITARY_BUTTON_TYPES.TRAIN_OUTLAW]: 'Train',
    [MILITARY_BUTTON_TYPES.TRAIN_HEAVY_INFANTRY]: 'Train',
    [MILITARY_BUTTON_TYPES.UPGRADE_HEAVY_INFANTRY]: 'Upgrade',
    [MILITARY_BUTTON_TYPES.TRAIN_SHOCKTROOPER]: 'Train',
    [MILITARY_BUTTON_TYPES.UPGRADE_SHOCKTROOPER]: 'Upgrade',
    [MILITARY_BUTTON_TYPES.TRAIN_SIEGETROOPER]: 'Train',
    [MILITARY_BUTTON_TYPES.TRAIN_MAGE]: 'Train',
    [MILITARY_BUTTON_TYPES.UPGRADE_MAGE]: 'Upgrade',
    [MILITARY_BUTTON_TYPES.TRAIN_ARCH_MAGE]: 'Train',
    [MILITARY_BUTTON_TYPES.TRAIN_THUNDERER]: 'Train',
    [MILITARY_BUTTON_TYPES.UPGRADE_THUNDERER]: 'Upgrade',
    [MILITARY_BUTTON_TYPES.TRAIN_THUNDERGUARD]: 'Train',
    [MILITARY_BUTTON_TYPES.UPGRADE_THUNDERGUARD]: 'Upgrade',
    [MILITARY_BUTTON_TYPES.TRAIN_DRAGONGUARD]: 'Train',
    [MILITARY_BUTTON_TYPES.DISABLED_TRAIN]: 'Upgrade',
    [MILITARY_BUTTON_TYPES.DISABLED_UPGRADE]: 'Upgrade',
}

export const MILITARY_BUTTON_COSTS: IButtonCostList = {
    /* TRAINING */
    [MILITARY_BUTTON_TYPES.TRAIN_SPEARMAN]: [
        { type: RESOURCE_TYPES.FOOD, cost: 400, },
        { type: RESOURCE_TYPES.IRON, cost: 100, },
    ],
    [MILITARY_BUTTON_TYPES.TRAIN_FOOTPAD]: [
        { type: RESOURCE_TYPES.WOOD, cost: 1000, },
        { type: RESOURCE_TYPES.GOLD, cost: 20, },
    ],
    [MILITARY_BUTTON_TYPES.TRAIN_HEAVY_INFANTRY]: [
        { type: RESOURCE_TYPES.FOOD, cost: 4000, },
        { type: RESOURCE_TYPES.STEEL, cost: 300, },
        { type: RESOURCE_TYPES.GOLD, cost: 100, },
    ],
    [MILITARY_BUTTON_TYPES.TRAIN_MAGE]: [
        { type: RESOURCE_TYPES.KNOWLEDGE, cost: 3000, },
        { type: RESOURCE_TYPES.GOLD, cost: 150, },
    ],
    [MILITARY_BUTTON_TYPES.TRAIN_THUNDERER]: [
        { type: RESOURCE_TYPES.COAL, cost: 3000, },
        { type: RESOURCE_TYPES.STEEL, cost: 2000 },
        { type: RESOURCE_TYPES.GOLD, cost: 1000, },
        { type: RESOURCE_TYPES.MITHRIL_ALLOY, cost: 10 },
    ],
    /* 
     *
        UPGRADING 
     *
    */
    [MILITARY_BUTTON_TYPES.UPGRADE_SPEARMAN]: [
        { type: RESOURCE_TYPES.FOOD, cost: 2000, },
        { type: RESOURCE_TYPES.STEEL, cost: 500, },
    ],
    [MILITARY_BUTTON_TYPES.UPGRADE_PIKEMAN]: [
        { type: RESOURCE_TYPES.ADAMANTITE_ALLOY, cost: 1000, },
        { type: RESOURCE_TYPES.GOLD, cost: 2000, },
    ],
    [MILITARY_BUTTON_TYPES.UPGRADE_FOOTPAD]: [
        { type: RESOURCE_TYPES.WOOD, cost: 10000, },
        { type: RESOURCE_TYPES.GOLD, cost: 1000, },
    ],
    [MILITARY_BUTTON_TYPES.UPGRADE_HEAVY_INFANTRY]: [
        { type: RESOURCE_TYPES.FOOD, cost: 20000, },
        { type: RESOURCE_TYPES.MITHRIL_ALLOY, cost: 100, },
    ],
    [MILITARY_BUTTON_TYPES.UPGRADE_SHOCKTROOPER]: [
        { type: RESOURCE_TYPES.FOOD, cost: 50000, },
        { type: RESOURCE_TYPES.STEEL, cost: 2000, },
        { type: RESOURCE_TYPES.GOLD, cost: 2500, },
        { type: RESOURCE_TYPES.ADAMANTITE_ALLOY, cost: 1500, },
    ],
    [MILITARY_BUTTON_TYPES.UPGRADE_MAGE]: [
        { type: RESOURCE_TYPES.KNOWLEDGE, cost: 50000, },
        { type: RESOURCE_TYPES.GOLD, cost: 5000, },
    ],
}

export const TRAIN_BUTTONS = new Set<string>([
    MILITARY_BUTTON_TYPES.TRAIN_HALBERDIER,
    MILITARY_BUTTON_TYPES.TRAIN_HEAVY_INFANTRY,
    MILITARY_BUTTON_TYPES.TRAIN_PIKEMAN,
    MILITARY_BUTTON_TYPES.TRAIN_FOOTPAD,
    MILITARY_BUTTON_TYPES.TRAIN_OUTLAW,
    MILITARY_BUTTON_TYPES.TRAIN_SHOCKTROOPER,
    MILITARY_BUTTON_TYPES.TRAIN_SIEGETROOPER,
    MILITARY_BUTTON_TYPES.TRAIN_SPEARMAN,
    MILITARY_BUTTON_TYPES.TRAIN_MAGE,
    MILITARY_BUTTON_TYPES.TRAIN_ARCH_MAGE,
    MILITARY_BUTTON_TYPES.TRAIN_THUNDERER,
    MILITARY_BUTTON_TYPES.TRAIN_THUNDERGUARD,
    MILITARY_BUTTON_TYPES.TRAIN_DRAGONGUARD,
])

export const UPGRADE_BUTTONS = new Set<string>([
    MILITARY_BUTTON_TYPES.UPGRADE_SPEARMAN,
    MILITARY_BUTTON_TYPES.UPGRADE_PIKEMAN,
    MILITARY_BUTTON_TYPES.UPGRADE_FOOTPAD,
    MILITARY_BUTTON_TYPES.UPGRADE_HEAVY_INFANTRY,
    MILITARY_BUTTON_TYPES.UPGRADE_SHOCKTROOPER,
    MILITARY_BUTTON_TYPES.UPGRADE_MAGE,
])