
export const GATHER_FOOD_AMOUNT = 1;
export const GATHER_WOOD_AMOUNT = 1;

export const WORKER_FOOD_CONSUMPTION = 5;

export const MANSION_COAL_CONSUMPTION = 1;
export const TAVERN_FOOD_CONSUMPTION = 10;

export const BONUSES = {
  WORKER_TAXATION: 0.5,
  HOUSE: 1,
  MANSION: 1,
  TAVERN: 1,
  SAWMILL: 0.05,
  GRANARY: 0.05,
  QUARRY: 0.05,
  UNIVERSITY: 0.05
}

export const CAPACITIES = {
  STORAGE: 200,
  WAREHOUSE: 1500,
  HUGE_WAREHOUSE: 10000,
  SAWMILL: 500,
  GRANARY: 500,
  QUARRY: 500,
  UNIVERSITY: 500,
}