
export const WORKER_FOOD_CONSUMPTION = 5;
export const IRON_SMELTER_ORE_INPUT = 100;
export const IRON_SMELTER_COAL_INPUT = 10;
export const IRON_SMELTER_IRON_OUTPUT = 1;
export const BLAST_FURNACE_IRON_INPUT = 10;
export const BLAST_FURNACE_COAL_INPUT = 5;
export const BLAST_FURNACE_STEEL_OUTPUT = 1;