import { RESOURCE_TYPES } from "./resourceTypes";

export const INDUSTRY_BUILDINGS = [
    RESOURCE_TYPES.IRON_SMELTER,
    RESOURCE_TYPES.BLAST_FURNACE,
];

export const IRON_SMELTER_ORE_INPUT = 100;
export const IRON_SMELTER_COAL_INPUT = 10;
export const IRON_SMELTER_IRON_OUTPUT = 1;
export const BLAST_FURNACE_IRON_INPUT = 10;
export const BLAST_FURNACE_COAL_INPUT = 50;
export const BLAST_FURNACE_STEEL_OUTPUT = 1;

export const IRON_SMELTER_INPUTS = {
    [RESOURCE_TYPES.RAW_ORE]: IRON_SMELTER_ORE_INPUT,
    [RESOURCE_TYPES.COAL]: IRON_SMELTER_COAL_INPUT,
}
export const BLAST_FURNACE_INPUTS = {
    [RESOURCE_TYPES.IRON]: BLAST_FURNACE_IRON_INPUT,
    [RESOURCE_TYPES.COAL]: BLAST_FURNACE_COAL_INPUT,
}
export const IRON_SMELTER_OUTPUTS = {
    [RESOURCE_TYPES.IRON]: IRON_SMELTER_IRON_OUTPUT,
}
export const BLAST_FURNACE_OUTPUTS = {
    [RESOURCE_TYPES.STEEL]: BLAST_FURNACE_STEEL_OUTPUT,
}
