import { blastFurnacesActivated, ironSmeltersActivated, magicFurnacesActivated, mithrilFurnacesActivated, workshopsActivated } from "~/store/resources";
import { RESOURCE_TYPES } from "./resourceTypes";

export const INDUSTRY_BUILDINGS = [
    RESOURCE_TYPES.WORKSHOP,
    RESOURCE_TYPES.IRON_SMELTER,
    RESOURCE_TYPES.BLAST_FURNACE,
    RESOURCE_TYPES.MITHRIL_FURNACE,
    RESOURCE_TYPES.MAGIC_FURNACE,
];

export const INDUSTRY_BUILDING_STORE_MAP = {
    [RESOURCE_TYPES.WORKSHOP]: workshopsActivated,
    [RESOURCE_TYPES.IRON_SMELTER]: ironSmeltersActivated,
    [RESOURCE_TYPES.BLAST_FURNACE]: blastFurnacesActivated,
    [RESOURCE_TYPES.MITHRIL_FURNACE]: mithrilFurnacesActivated,
    [RESOURCE_TYPES.MAGIC_FURNACE]: magicFurnacesActivated,
}

export const INDUSTRY_BUILDING_TITLES = {
    [RESOURCE_TYPES.WORKSHOP]: "Workshop",
    [RESOURCE_TYPES.IRON_SMELTER]: "Iron Smelter",
    [RESOURCE_TYPES.BLAST_FURNACE]: "Blast Furnace",
    [RESOURCE_TYPES.MITHRIL_FURNACE]: "Steel Furnace",
    [RESOURCE_TYPES.MAGIC_FURNACE]: "Magic Furnace",
}

export const WORKSHOP_WOOD_INPUT = 50;
export const WORKSHOP_WOOD_PLANK_OUTPUT = 1;

export const IRON_SMELTER_ORE_INPUT = 50;
export const IRON_SMELTER_COAL_INPUT = 5;
export const IRON_SMELTER_IRON_OUTPUT = 0.5;

export const BLAST_FURNACE_IRON_INPUT = 10;
export const BLAST_FURNACE_COAL_INPUT = 50;
export const BLAST_FURNACE_STEEL_OUTPUT = 1;
export const BLAST_FURNACE_ORE_OUTPUT = 100;

export const MITHRIL_FURNACE_COAL_INPUT = 500;
export const MITHRIL_FURNACE_STEEL_INPUT = 50;
export const MITHRIL_FURNACE_MITHRIL_INPUT = 1;
export const MITHRIL_FURNACE_MITHRIL_ALLOY_OUTPUT = 1;

export const MAGIC_FURNACE_MITHRIL_ALLOY_INPUT = 100;
export const MAGIC_FURNACE_ADAMANTITE_INPUT = 1;
export const MAGIC_FURNACE_ADAMANTITE_ALLOY_OUTPUT = 1;

export const WORKSHOP_INPUTS = {
    [RESOURCE_TYPES.WOOD]: WORKSHOP_WOOD_INPUT,
}
export const WORKSHOP_OUTPUTS = {
    [RESOURCE_TYPES.WOOD_PLANK]: WORKSHOP_WOOD_PLANK_OUTPUT,
}
export const IRON_SMELTER_INPUTS = {
    [RESOURCE_TYPES.RAW_ORE]: IRON_SMELTER_ORE_INPUT,
    [RESOURCE_TYPES.COAL]: IRON_SMELTER_COAL_INPUT,
}
export const IRON_SMELTER_OUTPUTS = {
    [RESOURCE_TYPES.IRON]: IRON_SMELTER_IRON_OUTPUT,
}
export const BLAST_FURNACE_INPUTS = {
    [RESOURCE_TYPES.IRON]: BLAST_FURNACE_IRON_INPUT,
    [RESOURCE_TYPES.COAL]: BLAST_FURNACE_COAL_INPUT,
}
export const BLAST_FURNACE_OUTPUTS = {
    [RESOURCE_TYPES.STEEL]: BLAST_FURNACE_STEEL_OUTPUT,
    [RESOURCE_TYPES.RAW_ORE]: BLAST_FURNACE_ORE_OUTPUT,
}
export const MITHRIL_FURNACE_INPUTS = {
    [RESOURCE_TYPES.COAL]: MITHRIL_FURNACE_COAL_INPUT,
    [RESOURCE_TYPES.STEEL]: MITHRIL_FURNACE_STEEL_INPUT,
    [RESOURCE_TYPES.MITHRIL]: MITHRIL_FURNACE_MITHRIL_INPUT,
}
export const MITHRIL_FURNACE_OUTPUTS = {
    [RESOURCE_TYPES.MITHRIL_ALLOY]: MITHRIL_FURNACE_MITHRIL_ALLOY_OUTPUT,
}
export const MAGIC_FURNACE_INPUTS = {
    [RESOURCE_TYPES.MITHRIL_ALLOY]: MAGIC_FURNACE_MITHRIL_ALLOY_INPUT,
    [RESOURCE_TYPES.ADAMANTITE]: MAGIC_FURNACE_ADAMANTITE_INPUT,
}
export const MAGIC_FURNACE_OUTPUTS = {
    [RESOURCE_TYPES.ADAMANTITE_ALLOY]: MAGIC_FURNACE_ADAMANTITE_ALLOY_OUTPUT,
}

export const INDUSTRY_INPUTS_MAP = {
    [RESOURCE_TYPES.WORKSHOP]: WORKSHOP_INPUTS,
    [RESOURCE_TYPES.IRON_SMELTER]: IRON_SMELTER_INPUTS,
    [RESOURCE_TYPES.BLAST_FURNACE]: BLAST_FURNACE_INPUTS,
    [RESOURCE_TYPES.MITHRIL_FURNACE]: MITHRIL_FURNACE_INPUTS,
    [RESOURCE_TYPES.MAGIC_FURNACE]: MAGIC_FURNACE_INPUTS,
}

export const RESOURCE_TO_RESOURCE_OUTPUT_MAP = {
    [RESOURCE_TYPES.WOOD_PLANK]: WORKSHOP_WOOD_PLANK_OUTPUT,
    [RESOURCE_TYPES.IRON]: IRON_SMELTER_IRON_OUTPUT,
    [RESOURCE_TYPES.STEEL]: BLAST_FURNACE_STEEL_OUTPUT,
    [RESOURCE_TYPES.RAW_ORE]: BLAST_FURNACE_ORE_OUTPUT,
    [RESOURCE_TYPES.MITHRIL_ALLOY]: MITHRIL_FURNACE_MITHRIL_ALLOY_OUTPUT,
    [RESOURCE_TYPES.ADAMANTITE_ALLOY]: MAGIC_FURNACE_ADAMANTITE_ALLOY_OUTPUT
}

export const RESOURCE_INPUT_TO_INDUSTRY_BUILDINGS_MAP = {
    [RESOURCE_TYPES.WOOD]: [RESOURCE_TYPES.WORKSHOP],
    [RESOURCE_TYPES.RAW_ORE]: [RESOURCE_TYPES.IRON_SMELTER],
    [RESOURCE_TYPES.COAL]: [RESOURCE_TYPES.IRON_SMELTER, RESOURCE_TYPES.BLAST_FURNACE, RESOURCE_TYPES.MITHRIL_FURNACE],
    [RESOURCE_TYPES.IRON]: [RESOURCE_TYPES.BLAST_FURNACE],
    [RESOURCE_TYPES.STEEL]: [RESOURCE_TYPES.MITHRIL_FURNACE],
    [RESOURCE_TYPES.MITHRIL]: [RESOURCE_TYPES.MITHRIL_FURNACE],
    [RESOURCE_TYPES.MITHRIL_ALLOY]: [RESOURCE_TYPES.MAGIC_FURNACE],
    [RESOURCE_TYPES.ADAMANTITE]: [RESOURCE_TYPES.MAGIC_FURNACE],
}

export const RESOURCE_OUTPUT_TO_INDUSTRY_BUILDING_MAP = {
    [RESOURCE_TYPES.WOOD_PLANK]: RESOURCE_TYPES.WORKSHOP,
    [RESOURCE_TYPES.IRON]: RESOURCE_TYPES.IRON_SMELTER,
    [RESOURCE_TYPES.STEEL]: RESOURCE_TYPES.BLAST_FURNACE,
    [RESOURCE_TYPES.MITHRIL_ALLOY]: RESOURCE_TYPES.MITHRIL_FURNACE,
    [RESOURCE_TYPES.ADAMANTITE_ALLOY]: RESOURCE_TYPES.MAGIC_FURNACE,
}