import { blastFurnacesActivated, ironSmeltersActivated, workshopsActivated } from "~/store/resources";
import { RESOURCE_TYPES } from "./resourceTypes";

export const INDUSTRY_BUILDINGS = [
    RESOURCE_TYPES.WORKSHOP,
    RESOURCE_TYPES.IRON_SMELTER,
    RESOURCE_TYPES.BLAST_FURNACE,
];

export const INDUSTRY_BUILDING_STORE_MAP = {
    [RESOURCE_TYPES.WORKSHOP]: workshopsActivated,
    [RESOURCE_TYPES.IRON_SMELTER]: ironSmeltersActivated,
    [RESOURCE_TYPES.BLAST_FURNACE]: blastFurnacesActivated,
}

export const INDUSTRY_BUILDING_TITLES = {
    [RESOURCE_TYPES.WORKSHOP]: "Workshop",
    [RESOURCE_TYPES.IRON_SMELTER]: "Iron Smelter",
    [RESOURCE_TYPES.BLAST_FURNACE]: "Blast Furnace",
}

export const WORKSHOP_WOOD_INPUT = 500;
export const WORKSHOP_WOOD_PLANK_OUTPUT = 1;
export const IRON_SMELTER_ORE_INPUT = 100;
export const IRON_SMELTER_COAL_INPUT = 10;
export const IRON_SMELTER_IRON_OUTPUT = 1;
export const BLAST_FURNACE_IRON_INPUT = 10;
export const BLAST_FURNACE_COAL_INPUT = 50;
export const BLAST_FURNACE_STEEL_OUTPUT = 1;

export const WORKSHOP_INPUTS = {
    [RESOURCE_TYPES.WOOD]: WORKSHOP_WOOD_INPUT,
}
export const WORKSHOP_OUTPUTS = {
    [RESOURCE_TYPES.WOOD_PLANK]: WORKSHOP_WOOD_PLANK_OUTPUT,
}
export const IRON_SMELTER_INPUTS = {
    [RESOURCE_TYPES.RAW_ORE]: IRON_SMELTER_ORE_INPUT,
    [RESOURCE_TYPES.COAL]: IRON_SMELTER_COAL_INPUT,
}
export const IRON_SMELTER_OUTPUTS = {
    [RESOURCE_TYPES.IRON]: IRON_SMELTER_IRON_OUTPUT,
}
export const BLAST_FURNACE_INPUTS = {
    [RESOURCE_TYPES.IRON]: BLAST_FURNACE_IRON_INPUT,
    [RESOURCE_TYPES.COAL]: BLAST_FURNACE_COAL_INPUT,
}
export const BLAST_FURNACE_OUTPUTS = {
    [RESOURCE_TYPES.STEEL]: BLAST_FURNACE_STEEL_OUTPUT,
}
