export const RESOURCE_TYPES: Record<string, string> = {
    FOOD: 'food',
    WOOD: 'wood',
    KNOWLEDGE: 'knowledge',
    RAW_ORE: 'rawOre',
    COAL: 'coal',
    WOOD_PLANK: 'woodPlank',
    IRON: 'iron',
    GOLD: 'gold',
    FURS: 'furs',
    STEEL: 'steel',
    MITHRIL: 'mithril',
    MITHRIL_ALLOY: 'mithril alloy',
    ADAMANTITE: 'adamantite',
    ADAMANTITE_ALLOY: 'adamantite alloy',
    FARM: 'farm',
    TREE_FARM: 'treeFarm',
    HOUSE: 'home',
    MANSION: 'mansion',
    TAVERN: 'tavern',
    ATHENAEUM: 'athenaeum',
    STORAGE: 'storage',
    WAREHOUSE: 'warehouse',
    GRANARY: 'granary',
    SAWMILL: 'sawmill',
    QUARRY: 'quarry',
    UNIVERSITY: 'university',
    WORKSHOP: 'workshop',
    IRON_SMELTER: 'ironSmelter',
    BLAST_FURNACE: 'blastFurnace',
    MITHRIL_FURNACE: 'mithrilFurnace',
    MAGIC_FURNACE: 'magicFurnace',
    ATTRACTIVE_HOUSE: 'attractiveHouse',
    SINATRAS_SHATTERED_ARMOR: 'sinatraShatteredArmor',
    HALBERD_OF_ADUN: 'halberdOfAdun',
    LUTAREZS_WARHAMMER: 'lutarezWarhammer',
    AEDUS_TOME_OF_KNOWLEDGE: 'aedusTomeOfKnowledge',
    GEM_OF_ETHEREALITY: 'gemOfEthereality'
}

export const RESOURCE_NAMES: Record<string, string> = {
    [RESOURCE_TYPES.FOOD]: 'food',
    [RESOURCE_TYPES.FARM]: 'farms',
    [RESOURCE_TYPES.WOOD]: 'wood',
    [RESOURCE_TYPES.TREE_FARM]: 'tree farms',
    [RESOURCE_TYPES.STORAGE]: 'storages',
    [RESOURCE_TYPES.HOUSE]: 'homes',
    [RESOURCE_TYPES.MANSION]: 'mansions',
    [RESOURCE_TYPES.TAVERN]: 'taverns',
    [RESOURCE_TYPES.ATHENAEUM]: 'athenaeum',
    [RESOURCE_TYPES.KNOWLEDGE]: 'knowledge',
    [RESOURCE_TYPES.RAW_ORE]: 'raw ore',
    [RESOURCE_TYPES.COAL]: 'coal',
    [RESOURCE_TYPES.WOOD_PLANK]: 'wood planks',
    [RESOURCE_TYPES.IRON]: 'iron',
    [RESOURCE_TYPES.GOLD]: 'gold',
    [RESOURCE_TYPES.FURS]: 'furs',
    [RESOURCE_TYPES.STEEL]: 'steel',
    [RESOURCE_TYPES.MITHRIL]: 'mithril',
    [RESOURCE_TYPES.MITHRIL_ALLOY]: 'mithril alloy',
    [RESOURCE_TYPES.ADAMANTITE]: 'adamantite',
    [RESOURCE_TYPES.ADAMANTITE_ALLOY]: 'adamantite alloy',
    [RESOURCE_TYPES.WAREHOUSE]: 'warehouses',
    [RESOURCE_TYPES.GRANARY]: 'granaries',
    [RESOURCE_TYPES.SAWMILL]: 'sawmills',
    [RESOURCE_TYPES.QUARRY]: 'quarries',
    [RESOURCE_TYPES.UNIVERSITY]: 'universities',
    [RESOURCE_TYPES.WORKSHOP]: 'workshops',
    [RESOURCE_TYPES.IRON_SMELTER]: 'smelters',
    [RESOURCE_TYPES.BLAST_FURNACE]: 'blast furnaces',
    [RESOURCE_TYPES.MITHRIL_FURNACE]: 'mithril furnaces',
    [RESOURCE_TYPES.MAGIC_FURNACE]: 'magic furnaces',
    [RESOURCE_TYPES.SINATRAS_SHATTERED_ARMOR]: `Sinatra's Shattered Armor`,
    [RESOURCE_TYPES.HALBERD_OF_ADUN]: 'Halberd of Adun',
    [RESOURCE_TYPES.LUTAREZS_WARHAMMER]: `Lutarez's Warhammer`,
    [RESOURCE_TYPES.AEDUS_TOME_OF_KNOWLEDGE]: `Aedus' Tome of Knowledge`,
    [RESOURCE_TYPES.GEM_OF_ETHEREALITY]: `Gem of Ethereality`,
}

export const BUILDINGS: Set<string> = new Set([
    RESOURCE_TYPES.FARM,
    RESOURCE_TYPES.TREE_FARM,
    RESOURCE_TYPES.STORAGE,
    RESOURCE_TYPES.HOUSE,
    RESOURCE_TYPES.ATHENAEUM,
    RESOURCE_TYPES.WAREHOUSE,
    RESOURCE_TYPES.GRANARY,
    RESOURCE_TYPES.SAWMILL,
    RESOURCE_TYPES.QUARRY,
    RESOURCE_TYPES.UNIVERSITY,
    RESOURCE_TYPES.WORKSHOP,
    RESOURCE_TYPES.IRON_SMELTER,
    RESOURCE_TYPES.BLAST_FURNACE,
    RESOURCE_TYPES.MITHRIL_FURNACE,
    RESOURCE_TYPES.MAGIC_FURNACE,
])

export const SPECIAL_RESOURCES = new Set<string>([
    RESOURCE_TYPES.SINATRAS_SHATTERED_ARMOR,
    RESOURCE_TYPES.HALBERD_OF_ADUN,
    RESOURCE_TYPES.LUTAREZS_WARHAMMER,
    RESOURCE_TYPES.AEDUS_TOME_OF_KNOWLEDGE,
])

export const GENERATABLE_RESOURCES = [
    RESOURCE_TYPES.FOOD,
    RESOURCE_TYPES.WOOD,
    RESOURCE_TYPES.KNOWLEDGE,
    RESOURCE_TYPES.RAW_ORE,
    RESOURCE_TYPES.COAL,
    RESOURCE_TYPES.WOOD_PLANK,
    RESOURCE_TYPES.IRON,
    RESOURCE_TYPES.GOLD,
    RESOURCE_TYPES.FURS,
    RESOURCE_TYPES.STEEL,
    RESOURCE_TYPES.MITHRIL,
    RESOURCE_TYPES.MITHRIL_ALLOY,
    RESOURCE_TYPES.ADAMANTITE,
    RESOURCE_TYPES.ADAMANTITE_ALLOY
]

export const RESOURCE_GENERATOR_MAP = {
    [RESOURCE_TYPES.FOOD]: RESOURCE_TYPES.FARM,
    [RESOURCE_TYPES.WOOD]: RESOURCE_TYPES.TREE_FARM,

}
