export const UNIT_TYPES = {
    SPEARMAN: 'spearman',
    PIKEMAN: 'pikeman',
    HALBERDIER: 'halberdier',
    FOOTPAD: 'footpad',
    OUTLAW: 'outlaw',
    HEAVY_INFANTRY: 'heavyInfantry',
    SHOCKTROOPER: 'shocktrooper',
    SIEGETROOPER: 'siegetrooper',
    MAGE: 'mage',
    ARCH_MAGE: 'archMage',
    NECROMANCER: 'necromancer',
    THUNDERER: 'thunderer',
    THUNDERGUARD: 'thunderguard',
    DRAGONGUARD: 'dragonguard',
    WOLF1: 'wolf1',
    WOLF2: 'wolf2',
    WOLF3: 'wolf3',
    SKELETON: 'skeleton',
    SKELETON_ARCHER: 'skeletonArcher',
    BAT: 'bat',
    GHOST: 'ghost',
    SHADOW: 'shadow',
    GHAST: 'ghast',
}